Update DocumenterVitepress compat in docs
LuxDL/Lux.jl pull request #654
Opened 2024-05-17 18:56 UTC by asinghvi17

Surprised CompatHelper didn't pick this up...

2024-05-17 20:16 UTC, avik-pal commented
https://buildkite.com/julialang/lux-dot-jl/builds/2169#018f87e9-ecbf-4f8f-b31f-08487e6cea15/571-7457 is failing so I bounded it

2024-05-17 20:21 UTC, asinghvi17 commented
Ah right, forgot about that.  Will update this PR once I've pushed a fix.

2024-06-01 21:19 UTC, avik-pal requested changes

2024-06-01 21:19 UTC, avik-pal commented on docs/Project.toml
>  [compat]
```suggestion
```

2024-06-01 21:19 UTC, avik-pal commented on docs/Project.toml
> +DocumenterVitepress = "0.0.19, 0.0.20"
```suggestion
```

2024-06-15 12:59 UTC, asinghvi17 commented
Looks like the doc build worked at least.

2024-06-15 14:14 UTC, merged