Add activation functions doc reference
LuxDL/Lux.jl pull request #694
Opened 2024-06-10 15:45 UTC by NeroBlackstone

2024-06-11 03:06 UTC, avik-pal requested changes

2024-06-11 03:06 UTC, avik-pal commented on docs/src/.vitepress/config.mts
> +                    },
Put it under `Building Blocks` as:

```
{ text: 'NNlib', link: 'https://fluxml.ai/NNlib.jl/dev/' },
{ text: 'Activation Functions', link: 'https://fluxml.ai/NNlib.jl/dev/reference/#Activation-Functions' }
```

2024-06-12 13:07 UTC, NeroBlackstone commented
Add docs for [Parallel](https://lux.csail.mit.edu/stable/api/Lux/layers#Lux.Parallel)

2024-06-12 14:35 UTC, NeroBlackstone commented
Add [FlattenLayer](https://lux.csail.mit.edu/stable/api/Lux/layers#Lux.FlattenLayer) Example

2024-06-12 15:31 UTC, NeroBlackstone commented
Add [ReshapeLayer](https://lux.csail.mit.edu/stable/api/Lux/layers#Lux.ReshapeLayer) docs

2024-06-13 01:17 UTC, avik-pal commented
Doctests are failing, you would want to compare sizes or something that doesn't vary due to randomness. Else there is a way to avoid checking exact values via Documenter.jl but I don't remember the exact syntax for that

2024-06-13 09:55 UTC, NeroBlackstone commented
The error output is so long that I can't locate the problem. I removed the random numbers in `jldoctest`, or directly removed `jldoctest` to `julia`, but I manually tested all the added example codes and there was no problem.

2024-06-14 00:35 UTC, avik-pal commented on src/layers/containers.jl
> +```
```suggestion
```jldoctest
julia> model = Parallel(nothing,Dense(2,1),Dense(2,1))
Parallel(
    layer_1 = Dense(2 => 1),            # 3 parameters
    layer_2 = Dense(2 => 1),            # 3 parameters
)         # Total: 6 parameters,
          #        plus 0 states.

julia> using Random;
       rng = Random.seed!(123);
       ps, st = Lux.setup(rng, model);
       x1 = randn(rng,Float32,2);
       x2 = randn(rng,Float32,2);

julia> size.(first(model((x1, x2),ps,st)))
((1,), (1,))
```
```

2024-06-15 20:27 UTC, avik-pal commented
Thanks for these updates, I rebased it in https://github.com/LuxDL/Lux.jl/pull/702/. Will merge it there.

2024-06-15 20:27 UTC, closed without merging