Add ReverseSequence
LuxDL/Lux.jl pull request #698
Opened 2024-06-12 17:37 UTC by NeroBlackstone

I don't know if this is the correct implementation

2024-06-13 02:51 UTC, avik-pal requested changes
Let's redesign the interface a bit. I would default the `dims` to `nothing`. The behavior for that would be:

1. If the input is `AbstractVector{T}` and `!isbitstype(T)` then we simply call `Iterators.reverse` (note this is lazy)
2. For bitstype AbstractVector, call `reverse(x)`.
3. For other arrays, it calls `reverse(x; dims=ndims(x) - 1)`.

This essentially prevents unnecessary copies. For eg, for Bidirectional RNN we can simply construct an iterator once and make a lazy reverse iterator using this API without copying the entire array.

If `dims` is specified,

1. `AbstractVector{T}` and `!isbitstype(T)` throws an error
2. All other array inputs call `reverse(x; dims=r.dims)`

2024-06-13 02:51 UTC, avik-pal commented on src/layers/basic.jl
> +  return reverse(x;dims = r.dims), st
`r.dim`.

Also formatting is off

2024-06-13 14:25 UTC, NeroBlackstone commented
> If `dims` is specified,
> 
> 1. `AbstractVector{T}` and `!isbitstype(T)` throws an error

Hi, I'm curious why `isbitstype()` is needed here. For any 1D array, we can't specify `dim` right? So why we need `isbitstype()`, it would be nice if you could give an example with specific code. Thank you very much.

2024-06-13 17:28 UTC, NeroBlackstone commented
I have updated the implementation according to your guidance, except for the doubtful points above.

2024-06-13 17:42 UTC, NeroBlackstone commented
test failed on gpu, I can't reproduce on local since I don't have AMDGPU or CUDA devices...

2024-06-13 18:04 UTC, ludvigk commented
I think it fails because `Base.Iterators.Reverse{CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}}` is not `isbitstype`. CUDA doesn't like that.  Even a minimal example like this fails for that reason:
```julia
g = CUDA.zeros(1)
gr = Iterators.reverse(g)
g .* gr
```

2024-06-13 18:26 UTC, ludvigk commented
Using `reverse` instead of `Iterators.reverse` on arrays of type `GPUArraysCore.AbstractGPUArray` should fix this.

2024-06-13 19:02 UTC, NeroBlackstone commented
My bad, look like test all passed now.

Please let me know if any other changes are needed

2024-06-14 00:28 UTC, avik-pal commented on src/layers/basic.jl
> +	return reverse(x; dims = r.dim), st
Run the formatter; tabs and spaces are inconsistent.

2024-06-14 00:32 UTC, avik-pal commented on src/layers/basic.jl
> +	throw(DimensionMismatch(lazy"Cannot specify dimension when input is AbstractVector{T}"))
`dim = 1` is still valid. Error if it is not `1`

2024-06-15 16:05 UTC, NeroBlackstone commented
> Using `reverse` instead of `Iterators.reverse` on arrays of type `GPUArraysCore.AbstractGPUArray` should fix this.

I got a PC with GPU and test locally.

I found `Float64` works well but `Int` throws errors. Weird...

2024-06-15 20:30 UTC, avik-pal commented
Add this layer to the docs, also rebase with main. That will fix the doc build

2024-06-15 20:31 UTC, avik-pal commented on src/layers/basic.jl
> +  - `x`: AbstractArray of any shape.
```suggestion
  - `x`: AbstractArray.
```

2024-06-15 20:31 UTC, avik-pal commented on src/layers/basic.jl
> +    end
```suggestion
    r.dim == 1 && return reverse(x), st
    throw(DimensionMismatch(lazy"Cannot specify a dimension other than 1 for AbstractVector{T}"))
```

2024-06-15 20:31 UTC, avik-pal commented on src/layers/basic.jl
> +end
```suggestion
@kwdef struct ReverseSequence{D <: Union{Int, Nothing}} <: AbstractExplicitLayer
    dim::D = nothing
end
```

2024-06-16 04:38 UTC, NeroBlackstone commented
I noticed some test failures, should I follow up on this PR? Or leave all the rest to you？

2024-06-16 04:45 UTC, avik-pal commented
Github won't let me edit files directly. So if you add the docs to https://github.com/LuxDL/Lux.jl/blob/main/docs/src/api/Lux/layers.md#misc-helper-layers the build will pass

2024-06-16 06:09 UTC, avik-pal approved these changes

2024-06-16 06:09 UTC, merged